In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('mood.csv')

In [3]:
 df.head()

,sleep_hours,woke_up_on_time,coffee,breakfast,exercise,work_stress,workload,weather,social_interaction,screen_time,study_hours,productive_day,bad_event,good_event,music,outside_time,sleep_quality,mood
0,7,1,2,1,0,Low,Light,Windy,1,4.5,2.1,1,1,1,1,1.5,Fair,Happy
1,7,1,1,1,0,High,Moderate,Sunny,1,3.3,5.9,1,0,1,1,2.1,Poor,Calm
2,8,1,1,1,0,Medium,Moderate,Rainy,0,3.4,2.7,1,0,1,1,2.4,Poor,Calm
3,8,1,2,1,1,Medium,Moderate,Snowy,1,4.6,4.2,1,0,1,1,1.7,Good,Happy
4,4,1,3,0,0,Medium,Heavy,Rainy,1,9.6,1.6,0,1,1,1,0.1,Poor,Sad

In [4]:
 df.sample(5)

,sleep_hours,woke_up_on_time,coffee,breakfast,exercise,work_stress,workload,weather,social_interaction,screen_time,study_hours,productive_day,bad_event,good_event,music,outside_time,sleep_quality,mood
201,6,1,2,1,0,High,Moderate,Snowy,1,8.2,2.0,0,1,0,0,0.7,Fair,Sad
204,7,0,1,0,0,High,Heavy,Rainy,0,9.3,2.2,0,0,1,0,1.2,Excellent,Annoyed
194,9,1,1,1,0,Medium,Moderate,Cloudy,1,3.2,4.7,1,0,0,1,2.8,Good,Calm
356,4,1,0,1,0,High,Moderate,Windy,0,8.6,0.8,0,1,0,0,0.7,Poor,Annoyed
189,8,1,1,1,0,Low,Heavy,Cloudy,1,3.5,3.7,1,0,1,1,1.4,Good,Happy

In [5]:
df.shape

(500, 18)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sleep_hours         500 non-null    int64
 1   woke_up_on_time     500 non-null    int64
 2   coffee              500 non-null    int64
 3   breakfast           500 non-null    int64
 4   exercise            500 non-null    int64
 5   work_stress         500 non-null    str
 6   workload            500 non-null    str
 7   weather             500 non-null    str
 8   social_interaction  500 non-null    int64
 9   screen_time         500 non-null    float64
 10  study_hours         500 non-null    float64
 11  productive_day      500 non-null    int64
 12  bad_event           500 non-null    int64
 13  good_event          500 non-null    int64
 14  music               500 non-null    int64
 15  outside_time        500 non-null    float64
 16  sleep_quality       500 non-null    str
 17  mood                500 non-null    str
dtypes: float64(3), int64(10), str(5)
memory usage: 83.2 KB

In [7]:
df.describe()

,sleep_hours,woke_up_on_time,coffee,breakfast,exercise,social_interaction,screen_time,study_hours,productive_day,bad_event,good_event,music,outside_time
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,7.038000,0.656000,1.488000,0.732000,0.564000,0.680000,5.195000,2.999000,0.628000,0.292000,0.680000,0.824000,1.709200
std,1.515635,0.475517,0.804457,0.443361,0.496384,0.466943,2.104208,1.656837,0.483822,0.455138,0.466943,0.381202,0.970876
min,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.000000,0.000000,1.000000,0.000000,0.000000,0.000000,3.500000,1.600000,0.000000,0.000000,0.000000,1.000000,0.900000
50%,7.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.900000,2.800000,1.000000,0.000000,1.000000,1.000000,1.600000
75%,8.000000,1.000000,2.000000,1.000000,1.000000,1.000000,6.600000,4.400000,1.000000,1.000000,1.000000,1.000000,2.500000
max,9.000000,1.000000,3.000000,1.000000,1.000000,1.000000,10.000000,6.000000,1.000000,1.000000,1.000000,1.000000,3.500000

In [8]:
df.isnull().sum()

sleep_hours           0
woke_up_on_time       0
coffee                0
breakfast             0
exercise              0
work_stress           0
workload              0
weather               0
social_interaction    0
screen_time           0
study_hours           0
productive_day        0
bad_event             0
good_event            0
music                 0
outside_time          0
sleep_quality         0
mood                  0
dtype: int64

In [9]:
df["mood"].value_counts()

mood
Happy      189
Calm       125
Annoyed     98
Sad         88
Name: count, dtype: int64

In [10]:
X=df.drop(columns=["mood"])
X.shape
X.sample(5)

,sleep_hours,woke_up_on_time,coffee,breakfast,exercise,work_stress,workload,weather,social_interaction,screen_time,study_hours,productive_day,bad_event,good_event,music,outside_time,sleep_quality
302,4,1,3,1,0,Low,Moderate,Rainy,1,5.4,1.3,0,1,0,1,0.2,Excellent
83,7,0,1,1,0,Low,Heavy,Snowy,0,5.3,4.6,1,1,1,1,2.2,Good
488,7,1,1,1,1,Medium,Heavy,Sunny,1,3.6,4.1,1,1,1,1,1.0,Good
379,7,1,3,1,0,Medium,Light,Rainy,0,6.9,1.1,0,1,0,0,0.8,Excellent
303,8,1,2,1,1,Low,Moderate,Windy,1,2.1,2.9,1,0,1,1,1.5,Excellent

In [11]:
Y=df["mood"]
Y.shape
Y.sample(5)

496      Happy
147        Sad
158    Annoyed
194       Calm
369    Annoyed
Name: mood, dtype: str

In [12]:
X_train,X_test,Y_train,Y_test= train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2,random_state=42)

In [13]:
X_train.head()

,sleep_hours,woke_up_on_time,coffee,breakfast,exercise,work_stress,workload,weather,social_interaction,screen_time,study_hours,productive_day,bad_event,good_event,music,outside_time,sleep_quality
249,7,1,2,1,1,Low,Moderate,Sunny,1,2.2,5.3,1,1,1,1,1.4,Good
433,9,0,1,1,1,Low,Heavy,Sunny,1,3.1,2.7,1,0,1,1,2.7,Good
19,9,1,1,1,0,Low,Moderate,Sunny,0,2.2,2.2,1,1,1,1,1.2,Good
322,8,1,1,1,1,Medium,Moderate,Sunny,0,3.7,5.1,1,0,1,1,3.1,Fair
332,5,1,3,0,0,High,Moderate,Windy,1,6.8,2.1,0,0,1,1,0.2,Poor

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
transformer = ColumnTransformer(
    transformers=[
        ('tnf1', OrdinalEncoder(
            categories=[['Low', 'Medium', 'High']]
        ), ['work_stress']),

        ('tnf2', OrdinalEncoder(
            categories=[['Light', 'Moderate', 'Heavy']]
        ), ['workload']),
        ('tnf3', OneHotEncoder(sparse_output=False,drop='first'), ['weather']),

        ('tnf4', OrdinalEncoder(
            categories=[['Poor', 'Fair', 'Good', 'Excellent']]
        ), ['sleep_quality'])
        
    ],
    remainder='passthrough'
)

In [15]:
X_train_encoded = transformer.fit_transform(X_train)
X_test_encoded = transformer.transform(X_test)

In [16]:
X_train_encoded.shape

(400, 20)

In [17]:
X_test_encoded.shape

(100, 20)

In [18]:
model = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    min_samples_split=10,
    min_samples_leaf=8,
    max_features='sqrt',
    random_state=42
)

model.fit(X_train_encoded, Y_train)

print("Training accuracy:", model.score(X_train_encoded, Y_train))
print("Testing accuracy:", model.score(X_test_encoded, Y_test))

Training accuracy: 0.7025
Testing accuracy: 0.56

In [19]:
importances = pd.Series(
    model.feature_importances_,
    index=transformer.get_feature_names_out()
)

print(importances.sort_values(ascending=False))

remainder__productive_day        0.217472
remainder__screen_time           0.195283
remainder__study_hours           0.187768
remainder__outside_time          0.120103
remainder__sleep_hours           0.095006
tnf4__sleep_quality              0.032843
tnf1__work_stress                0.025925
remainder__coffee                0.021848
remainder__exercise              0.017073
remainder__breakfast             0.015971
tnf2__workload                   0.012817
remainder__good_event            0.012198
remainder__bad_event             0.011510
remainder__social_interaction    0.010548
remainder__woke_up_on_time       0.008163
tnf3__weather_Sunny              0.006275
tnf3__weather_Rainy              0.004659
remainder__music                 0.003634
tnf3__weather_Windy              0.000849
tnf3__weather_Snowy              0.000057
dtype: float64

In [20]:
new_data = pd.DataFrame({
    'sleep_hours': [8],
    'woke_up_on_time': [1],
    'coffee': [2],
    'breakfast': [1],
    'exercise': [1],
    'work_stress': ['Low'],
    'workload': ['Light'],
    'weather': ['Sunny'],
    'social_interaction': [2],
    'screen_time': [3.5],
    'study_hours': [2],
    'productive_day': [1],
    'bad_event': [0],
    'good_event': [2],
    'music': [1],
    'outside_time': [2.5],
    'sleep_quality': ['Good']
})
new_data_encoded = transformer.transform(new_data)
prediction = model.predict(new_data_encoded)

print("Predicted mood:", prediction[0])

Predicted mood: Happy